//https://www.w3.org/TR/CSS2/propidx.html
#define CSS_PROP_MAP { \
	_MAP(AZIMUTH,               "azimuth"), \
	_MAP(BACKGROUND,            "background"), \
	_MAP(BACKGROUND_ATTACHMENT, "background-attachment"), \
	_MAP(BACKGROUND_COLOR,      "background-color"), \
	_MAP(BACKGROUND_IMAGE,      "background-image"), \
	_MAP(BACKGROUND_POSITION,   "background-position"), \
	_MAP(BACKGROUND_REPEAT,     "background-repeat"), \
	_MAP(BORDER,                "border"), \
	_MAP(BORDER_BOTTOM,         "border-bottom"), \
	_MAP(BORDER_BOTTOM_COLOR,   "border-bottom-color"), \
	_MAP(BORDER_BOTTOM_STYLE,   "border-bottom-style"), \
	_MAP(BORDER_BOTTOM_WIDTH,   "border-bottom-width"), \
	_MAP(BORDER_COLLAPSE,       "border-collapse"), \
	_MAP(BORDER_COLOR,          "border-color"), \
	_MAP(BORDER_LEFT,           "border-left"), \
	_MAP(BORDER_LEFT_COLOR,     "border-left-color"), \
	_MAP(BORDER_LEFT_STYLE,     "border-left-style"), \
	_MAP(BORDER_LEFT_WIDTH,     "border-left-width"), \
	_MAP(BORDER_RIGHT,          "border-right"), \
	_MAP(BORDER_RIGHT_COLOR,    "border-right-color"), \
	_MAP(BORDER_RIGHT_STYLE,    "border-right-style"), \
	_MAP(BORDER_RIGHT_WIDTH,    "border-right-width"), \
	_MAP(BORDER_SPACING,        "border-spacing"), \
	_MAP(BORDER_STYLE,          "border-style"), \
	_MAP(BORDER_TOP,            "border-top"), \
	_MAP(BORDER_TOP_COLOR,      "border-top-color"), \
	_MAP(BORDER_TOP_STYLE,      "border-top-style"), \
	_MAP(BORDER_TOP_WIDTH,      "border-top-width"), \
	_MAP(BORDER_WIDTH,          "border-width"), \
	_MAP(BOTTOM,                "bottom"), \
	_MAP(CAPTION_SIDE,          "caption-side"), \
	_MAP(CLEAR,                 "clear"), \
	_MAP(CLIP,                  "clip"), \
	_MAP(COLOR,                 "color"), \
	_MAP(CONTENT,               "content"), \
	_MAP(COUNTER_INCREMENT,     "counter-increment"), \
	_MAP(COUNTER_RESET,         "counter-reset"), \
	_MAP(CUE,                   "cue"), \
	_MAP(CUE_AFTER,             "cue-after"), \
	_MAP(CUE_BEFORE,            "cue-before"), \
	_MAP(CURSOR,                "cursor"), \
	_MAP(DIRECTION,             "direction"), \
	_MAP(DISPLAY,               "display"), \
	_MAP(ELEVATION,             "elevation"), \
	_MAP(EMPTY_CELLS,           "empty-cells"), \
	_MAP(FLOAT,                 "float"), \
	_MAP(FONT,                  "font"), \
	_MAP(FONT_FAMILY,           "font-family"), \
	_MAP(FONT_SIZE,             "font-size"), \
	_MAP(FONT_STYLE,            "font-style"), \
	_MAP(FONT_VARIANT,          "font-variant"), \
	_MAP(FONT_WEIGHT,           "font-weight"), \
	_MAP(HEIGHT,                "height"), \
	_MAP(LEFT,                  "left"), \
	_MAP(LETTER_SPACING,        "letter-spacing"), \
	_MAP(LINE_HEIGHT,           "line-height"), \
	_MAP(LIST_STYLE,            "list-style"), \
	_MAP(LIST_STYLE_IMAGE,      "list-style-image"), \
	_MAP(LIST_STYLE_POSITION,   "list-style-position"), \
	_MAP(LIST_STYLE_TYPE,       "list-style-type"), \
	_MAP(MARGIN,                "margin"), \
	_MAP(MARGIN_BOTTOM,         "margin-bottom"), \
	_MAP(MARGIN_LEFT,           "margin-left"), \
	_MAP(MARGIN_RIGHT,          "margin-right"), \
	_MAP(MARGIN_TOP,            "margin-top"), \
	_MAP(MAX_HEIGHT,            "max-height"), \
	_MAP(MAX_WIDTH,             "max-width"), \
	_MAP(MIN_HEIGHT,            "min-height"), \
	_MAP(MIN_WIDTH,             "min-width"), \
	_MAP(ORPHANS,               "orphans"), \
	_MAP(OUTLINE,               "outline"), \
	_MAP(OUTLINE_COLOR,         "outline-color"), \
	_MAP(OUTLINE_STYLE,         "outline-style"), \
	_MAP(OUTLINE_WIDTH,         "outline-width"), \
	_MAP(OVERFLOW,              "overflow"), \
	_MAP(PADDING,               "padding"), \
	_MAP(PADDING_BOTTOM,        "padding-bottom"), \
	_MAP(PADDING_LEFT,          "padding-left"), \
	_MAP(PADDING_RIGHT,         "padding-right"), \
	_MAP(PADDING_TOP,           "padding-top"), \
	_MAP(PAGE_BREAK_AFTER,      "page-break-after"), \
	_MAP(PAGE_BREAK_BEFORE,     "page-break-before"), \
	_MAP(PAGE_BREAK_INSIDE,     "page-break-inside"), \
	_MAP(PAUSE,                 "pause"), \
	_MAP(PAUSE_AFTER,           "pause-after"), \
	_MAP(PAUSE_BEFORE,          "pause-before"), \
	_MAP(PITCH,                 "pitch"), \
	_MAP(PITCH_RANGE,           "pitch-range"), \
	_MAP(PLAY_DURING,           "play-during"), \
	_MAP(POSITION,              "position"), \
	_MAP(QUOTES,                "quotes"), \
	_MAP(RICHNESS,              "richness"), \
	_MAP(RIGHT,                 "right"), \
	_MAP(SPEAK,                 "speak"), \
	_MAP(SPEAK_HEADER,          "speak-header"), \
	_MAP(SPEAK_NUMERAL,         "speak-numeral"), \
	_MAP(SPEAK_PUNCTUATION,     "speak-punctuation"), \
	_MAP(SPEECH_RATE,           "speech-rate"), \
	_MAP(STRESS,                "stress"), \
	_MAP(TABLE_LAYOUT,          "table-layout"), \
	_MAP(TEXT_ALIGN,            "text-align"), \
	_MAP(TEXT_DECORATION,       "text-decoration"), \
	_MAP(TEXT_INDENT,           "text-indent"), \
	_MAP(TEXT_TRANSFORM,        "text-transform"), \
	_MAP(TOP,                   "top"), \
	_MAP(UNICODE_BIDI,          "unicode-bidi"), \
	_MAP(VERTICAL_ALIGN,        "vertical-align"), \
	_MAP(VISIBILITY,            "visibility"), \
	_MAP(VOICE_FAMILY,          "voice-family"), \
	_MAP(VOLUME,                "volume"), \
	_MAP(WHITE_SPACE,           "white-space"), \
	_MAP(WIDOWS,                "widows"), \
	_MAP(WIDTH,                 "width"), \
	_MAP(WORD_SPACING,          "word-spacing"), \
	_MAP(Z_INDEX,               "z-index"),\
}
